services:
  agent:
    environment:
      APP_ENV: prod
      LOG_LEVEL: INFO
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1g

  postgres:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2g

  redis:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512m
